version: '3.8'

services:
  redis:
    container_name: ad-service-redis
    image: redis:alpine
    hostname: hostname-redis
    ports:
      - "6379:6379"
  
  mysql: # See Also: https://hub.docker.com/_/mysql
    container_name: ad-service-mysqldb
    image: mysql
    hostname: hostname-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=sh
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=sh
      - MYSQL_PASSWORD=1234
      - TZ=Asia/Seoul
    ports:
      - "3306:3306"

  app:
    container_name: ad-service-practice
    image: ad-service-practice
    build: .
    volumes:
      - .:/app
    depends_on:
      - redis
      - mysql
    ports:
      - 8080:8080
    environment:
      - MYSQL_HOST=hostname-mysql
      - REDIS_HOST=hostname-redis
    command: |
      sh -c "./wait-for-it.sh mysql:3306 --
             ./wait-for-it.sh redis:6379"
